name: workflow
description: A visualized platform which is designed to create, develop and compile your standalone flutter module
homepage: https://github.com/wuba/magpie_workflow
version: 0.1.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  json_serializable: ^3.2.3
  json_annotation: ^3.0.0
  shared_preferences: ^0.5.6
  flutter_markdown: ^0.3.2
  qr_flutter: ^3.1.0
  dio: ^3.0.7
  provider: ^3.1.0+1
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.1.0
  http_server: ^0.9.8+3
  jaguar: ^2.4.36
  logging: ^0.11.3+2
  args: ^1.5.0
  process_run: ^0.10.6
  build_runner: ^1.0.0
  # 以下为tools的依赖, 放到此处是为了规避AS不识别问题
  archive: 2.0.11
  dwds: 0.7.9
  completion: 0.2.1+1
  coverage: 0.13.3+1
  crypto: 2.1.3
  file: 5.1.0
  intl: 0.16.0
  json_rpc_2: 2.1.0
  linter: 0.1.101
  meta: 1.1.8
  multicast_dns: 0.2.2
  mustache: 1.1.1
  package_config: 1.1.0
  platform: 2.2.1
  plugin: 0.2.0+3
  process: 3.0.12
  stack_trace: 1.9.3
  stream_channel: 2.0.0
  usage: 3.4.1
  vm_service_client: 0.2.6+2
  xml: 3.5.0
  yaml: 2.2.0

  #    flutter_goldens_client:
  #      path: ../flutter_goldens_client

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so when upgrading
  # this, make sure the tests are still running correctly.
  #test_api: 0.2.11
  #test_core: 0.2.15

  # Code generation dependencies
  build_runner_core: 4.1.0
  #dart_style: 1.3.3
  code_builder: 3.2.0
  build: 1.2.1
  build_modules: 2.6.3
  build_daemon: 2.1.0
  build_web_compilers: 2.7.1

  vm_service: 1.2.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - doc/help/
    - data/
    - build_number
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
