name: magpie_tool
description: Tools for building Flutter applications
homepage: https://flutter.dev
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.2.2 <3.0.0"

executables:
  magpie_tool:

dependencies:
  http_server: ^0.9.8+3
  jaguar: ^2.4.36
  logging: ^0.11.3+2
  args: ^1.5.0
  process_run: ^0.10.6
  dio: ^3.0.7
  #TODO 以下为tools的依赖
  archive: 2.0.11
  dwds: 0.7.9
  completion: 0.2.1+1
  coverage: 0.13.3+1
  crypto: 2.1.3
  file: 5.1.0
  http: 0.12.0+2
  intl: 0.16.0
  json_rpc_2: 2.1.0
  linter: 0.1.101
  meta: 1.1.8
  multicast_dns: 0.2.2
  mustache: 1.1.1
  package_config: 1.1.0
  platform: 2.2.1
  plugin: 0.2.0+3
  process: 3.0.12
  #quiver: 2.0.5
  stack_trace: 1.9.3
  stream_channel: 2.0.0
  usage: 3.4.1
  vm_service_client: 0.2.6+2
  #web_socket_channel: 1.1.0
  #webkit_inspection_protocol: 0.5.0
  xml: 3.5.0
  yaml: 2.2.0

#    flutter_goldens_client:
#      path: ../flutter_goldens_client

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so when upgrading
  # this, make sure the tests are still running correctly.
  #test_api: 0.2.11
  #test_core: 0.2.15

  # Code generation dependencies
  build_runner_core: 4.1.0
  #dart_style: 1.3.3
  code_builder: 3.2.0
  build: 1.2.1
  build_modules: 2.6.3
  build_daemon: 2.1.0
  #build_web_compilers: 2.7.1

  vm_service: 1.2.0

dev_dependencies:

  collection: 1.14.11
  mockito: 4.1.1
  file_testing: 2.1.0
  test: 1.9.4
  build_runner: 1.7.2
  build_vm_compilers: 1.0.4
  build_test: 0.10.9+1

  multi_server_socket: 1.0.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  node_preamble: 1.4.8 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  shelf_packages_handler: 1.0.4 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"

dartdoc:
  # Exclude this package from the hosted API docs.
  nodoc: true
